### ISSUE TITLE
Problem with "artnetnode.setStartingUniverse(2);"

### ISSUE THREAD

**Issue by Protezhe** [JuriaanGregor/ArtnetPixels#1]
I'm using Qlab 4 have a problem
line:  artnetnode.setStartingUniverse(2); do not change the number of universe. Alvays set "0"

**Comment by JuriaanGregor** [comment]
Hi there thanks for reaching out :)  You always should use the Starting Universe of 0. So what happens is that QLab is sending the start universe of 2, instead of 0. The library doesn't accept this sadly :( 

Quick fix : 
- In QLab 4 set the Start Universe to 0 (You can find this in the Patch window)

Here is a quick image that I found on Google.
https://figure53.com/docs/images/qlab4/settings-light-patch.png

If this still doesn't work, give me a shout. (I'm Windows based, so also can't help you further.)

- Juriaan

**Comment by JuriaanGregor** [comment]
It seems rStephan has helped you out :) Closing this issue.
